Feat/P2022 1427/ Automate retro screen test
intive/patronage22_mobile_auto_szczecin pull request #10
Opened 2022-03-12 17:52 UTC by KlaudiaLapcionek

2022-03-14 08:06 UTC, MarekPawlowskiQA commented on src/test/resources/features/retroScreen.feature
> +    Given User is logged in
I would put third And, this is still under given actions

2022-03-14 08:07 UTC, MarekPawlowskiQA commented on src/test/resources/features/retroScreen.feature
> +    And First retro board is opened
I would change to When

2022-03-14 08:07 UTC, MarekPawlowskiQA commented on src/test/resources/features/retroScreen.feature
> +    And Second retro board is opened
Same here

2022-03-14 08:08 UTC, MarekPawlowskiQA commented on src/test/java/com/intive/template/steps/RetroSteps.java
> +        Assert.assertTrue("Arrow button should be visible", retroPage.arrowBackButtonIsVisible());
Hamcrest or normall aserion, be consistent :D if evrybodky uses ham crest use ham crest

2022-03-14 08:16 UTC, MarekPawlowskiQA requested changes
Hamcrest + cucumber changes and we are ok :)

2022-03-14 10:10 UTC, KlaudiaLapcionek commented on src/test/java/com/intive/template/steps/RetroSteps.java
> +        Assert.assertTrue("Arrow button should be visible", retroPage.arrowBackButtonIsVisible());
Hi, in tests for mobile we used only normal assertions, so should I changed every normal assertion to Hamcrest or can I leave that?

2022-03-14 10:14 UTC, MarekPawlowskiAuto commented on src/test/java/com/intive/template/steps/RetroSteps.java
> +        Assert.assertTrue("Arrow button should be visible", retroPage.arrowBackButtonIsVisible());
Hmm good question, but consistency is consistency. Ok, we can assume mobile project uses only normal assertions not hamcrest ones.

2022-03-14 12:48 UTC, KlaudiaLapcionek commented on src/test/resources/features/retroScreen.feature
> +    Given User is logged in
I changed that.

2022-03-14 13:51 UTC, KlaudiaLapcionek commented on src/test/java/com/intive/template/pages/MainPage.java
> +    @AndroidFindBy(xpath = "//android.view.ViewGroup[@content-desc=\"Board screen\"]/androidx.recyclerview.widget.RecyclerView/android.view.ViewGroup[1]/android.widget.FrameLayout/android.view.ViewGr
Yes, I tried to creating a list with these elements and creating a "for" loop. But something didn't work so I created these steps for each element.

2022-03-16 07:05 UTC, MarekPawlowskiAuto approved these changes
lgtm :)

2022-03-16 07:08 UTC, MarekPawlowskiQA submitted a review, later dismissed
lgtm :)

2022-03-18 13:06 UTC, kacperpelc approved these changes
this is very nice commit

2022-03-18 13:11 UTC, KlaudiaLapcionek commented on src/test/java/com/intive/template/pages/RetroPage.java
> +            retroButtons.get(index).click();
I tried to change the for loop to an each for loop but I got an error:
`org.openqa.selenium.StaleElementReferenceException: Cached elements 'By.id: constraint_layout_board' do not exist in DOM anymore` 
@MarekPawlowskiQA can you take a look? Please tell me if you agree to this loop.

2022-03-20 16:24 UTC, MarekPawlowskiQA approved these changes
Sorry for late response, lgtm :)

2022-03-20 16:26 UTC, MarekPawlowskiQA commented on src/test/java/com/intive/template/pages/RetroPage.java
> +    public boolean openRetroBoardsAndCheckElements() {
lets merge this, but try to rethink this method, it is very hard to read with lot of !something elements , sometimes its better to create two methods where one will use another just for the fact it is easier to read.

2022-03-20 16:27 UTC, MarekPawlowskiQA commented on src/test/java/com/intive/template/pages/RetroPage.java
> +    public boolean openRetroBoardsAndCheckElements() {
do not change it in this PR, but if you find a way make another. If this will be problematic we can sit together.

2022-03-20 17:00 UTC, merged