User logout test automation
intive/patronage22_mobile_auto_szczecin pull request #6
Opened 2022-02-21 18:25 UTC by KacperLukasiewiczQA

2022-02-21 20:05 UTC, ospatrycja requested changes

2022-02-21 20:05 UTC, ospatrycja commented on src/test/resources/features/profileScreen.feature
> +    When User write email
I think in the logout test there should be a "given - User is logged in" block with login logic.

2022-02-21 20:05 UTC, ospatrycja commented on src/test/resources/features/profileScreen.feature
> +    And Click Logout
I think the results of the test are missing. In my opinion, the scenario should have "then" block

2022-02-22 15:49 UTC, KacperLukasiewiczQA commented on src/test/resources/features/profileScreen.feature
> +    When User write email
I corrected everything.

2022-02-22 16:56 UTC, KlaudiaLapcionek requested changes

2022-02-22 16:56 UTC, KlaudiaLapcionek commented on src/test/java/com/intive/template/pages/ProfilePage.java
> +    @AndroidFindBy(xpath = "//android.widget.ImageView[@content-desc=\"More options\"]")
You can find that element with simpler code: @AndroidFindBy(accessibility = "More options") - you have that element in MainPage too.

2022-02-22 16:56 UTC, KlaudiaLapcionek commented on src/test/resources/features/profileScreen.feature
> +
Could you add tag number of ticket with tests cases? According to Marek's request.

2022-02-22 17:45 UTC, KacperLukasiewiczQA commented on src/test/java/com/intive/template/pages/ProfilePage.java
> +    @AndroidFindBy(xpath = "//android.widget.ImageView[@content-desc=\"More options\"]")
I did this to avoid duplicating code. I didn't see Mark's message. All corrected

2022-02-22 17:58 UTC, ospatrycja requested changes

2022-02-22 17:58 UTC, ospatrycja commented on src/test/java/com/intive/template/pages/MainPage.java
> +    public void openMoreOptions(){
Minor thing - formatting could be corrected (missing empty line and white space)

2022-02-22 17:58 UTC, ospatrycja commented on src/test/java/com/intive/template/steps/ProfileSteps.java
> +    MainPage mainPage=new MainPage();
Minor thing: missing white spaces

2022-02-22 17:58 UTC, ospatrycja commented on src/test/resources/features/profileScreen.feature
> +    Then Click Logout
I think click logout is action, not result. The result will be like for example "Login screen is presented"

2022-02-22 18:17 UTC, KlaudiaLapcionek requested changes

2022-02-22 18:17 UTC, KlaudiaLapcionek commented on src/test/resources/features/profileScreen.feature
> +    Then Click Logout
Yes I agree with Patrycja and you can change "Click three dots button" to for example "Menu more options is opened"

2022-02-22 19:11 UTC, KacperLukasiewiczQA commented on src/test/resources/features/profileScreen.feature
> +    Then Click Logout
I corrected everything.

2022-02-23 08:16 UTC, KlaudiaLapcionek approved these changes
lgtm :)

2022-02-23 18:45 UTC, KrzysztofGajQA approved these changes
lgtm

2022-02-24 09:09 UTC, ospatrycja approved these changes
Looks good to me

2022-02-24 09:10 UTC, MarekPawlowskiAuto approved these changes
lgtm :)

2022-02-24 09:11 UTC, MarekPawlowskiQA approved these changes
lgtm, again : D

2022-02-24 12:07 UTC, merged