Feat/p2022 1171/main screen bottom bar test automation
intive/patronage22_mobile_auto_szczecin pull request #7
Opened 2022-02-26 16:56 UTC by KacperLukasiewiczQA

I corrected the formatting of the code and changed the method names to match better.

2022-02-28 16:07 UTC, MarekPawlowskiAuto commented on src/test/java/com/intive/template/pages/MainPage.java
>      @AndroidFindBy(xpath = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/androidx.drawerlayout.w
Ask Developers for accessibility_id, or change selector. This XPath will be  really unstable. This could be the cause tests are failing on BS (or not updated application on BS)

2022-02-28 17:46 UTC, KlaudiaLapcionek requested changes

2022-02-28 17:46 UTC, KlaudiaLapcionek commented on src/test/resources/features/bottomBar.feature
> +    Then "Boards" should be visible
The test failed because we have the text "Board Fragment" in the app. I know Justyna asked this and the Android developers told her they would change it and add new options here. But now you can change it to pass this test.

2022-02-28 17:46 UTC, KlaudiaLapcionek commented on src/test/resources/features/bottomBar.feature
> +    Then "History" should be visible
The test failed because we have the text "History Fragment" in the app.

2022-02-28 18:39 UTC, MarekPawlowskiAuto commented on src/test/resources/features/bottomBar.feature
> +    Then "Boards" should be visible
I would leave it if this is final, solution. We can merge this PR when the app will provide proper field.

2022-02-28 18:39 UTC, MarekPawlowskiAuto commented on src/test/resources/features/bottomBar.feature
> +    Then "Boards" should be visible
Still in the meantime i would ask the to add contet_desc ad remove this long xpath, on Mobile this will be really unstable.

2022-02-28 18:41 UTC, MarekPawlowskiAuto commented on src/test/resources/features/bottomBar.feature
> +    Then "Boards" should be visible
You can create task , for Android developers for that actions. Just describe precisely witch element you want to have

2022-02-28 18:57 UTC, KacperLukasiewiczQA commented on src/test/resources/features/bottomBar.feature
> +    Then "Boards" should be visible
I know everything, now I have a another problem.

2022-02-28 18:57 UTC, KacperLukasiewiczQA commented on src/test/resources/features/bottomBar.feature
> +    Then "Boards" should be visible
I will take care of everything

2022-02-28 18:59 UTC, KlaudiaLapcionek commented on src/test/resources/features/bottomBar.feature
> +    Then "Boards" should be visible
https://tracker.intive.com/jira/browse/P2022-1241 Justyna create this task for that, but they said to her the whole page would be changed so they won't just change one word.

2022-03-09 19:23 UTC, MarekPawlowskiQA reviewed
Tests still fail, why ? 
Try to rerun this on Github Actions and see why it is happening

2022-03-10 17:07 UTC, KlaudiaLapcionek approved these changes
Lgtm :)

2022-03-11 13:06 UTC, MarekPawlowskiQA approved these changes
lgtm :)

2022-03-11 20:41 UTC, merged